services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - path: .env
    container_name: workouts-backend_c
    ports:
      - '4001:4001'
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - path: .env
    container_name: workouts-frontend_c
    ports:
      - '3001:3001'
    stdin_open: true
    tty: true
    depends_on:
      - backend